version: "3.8"

services:
  postgres_dw:
    image: postgres:latest
    container_name: postgres_dw
    restart: always
    environment:
      POSTGRES_USER: dw_user
      POSTGRES_PASSWORD: dw_dss_BK@242
      POSTGRES_DB: sales_data_warehouse
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pgnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pgnet

volumes:
  postgres_data:

networks:
  pgnet:
